services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit for faster builds and better caching
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    # Mount source for development live reload
    volumes:
      - .:/polysensor

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Enable BuildKit for faster builds
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5173:5173"
    # Mount source for development live reload
    volumes:
      - ./frontend:/polysensor
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
